name: Publish NPM packages

on:
  push:
    branches:
      - main  # 或者是您想要触发此操作的分支名称，例如 'master'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ['package1', 'package2']  # 根据实际情况更新包名列表
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Check for changes in package
        id: check_changes
        run: |
          echo "Before: ${{ github.event.before }}"
          echo "After: ${{ github.event.after }}"
          PACKAGE_CHANGES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} -- ${{ matrix.package }} | wc -l)
          echo "Package changes: $PACKAGE_CHANGES"
          if [ $PACKAGE_CHANGES -gt 0 ]; then
            echo "publish=true" >> $GITHUB_ENV
          else
            echo "publish=false" >> $GITHUB_ENV
          fi

      - name: Create .npmrc file
        run: |
          echo "@cyrcime123:registry=https://registry.npmjs.org/" > ${{ matrix.package }}/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ${{ matrix.package }}/.npmrc

      - name: Publish package
        if: env.publish == 'true'
        run: cd ${{ matrix.package }} && npm ci && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
